### ISSUE TITLE
Specific PyTorch version

### ISSUE THREAD

**Issue by ekorman** [puhsu/tabular-dl-pretrain-objectives#1]
The command
```shell
pip install torch==1.11.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
```
in the readme fails with error `ERROR: No matching distribution found for torch==1.11.1+cu111`  because it looks like version 1.11.1 is not available.

**Comment by puhsu** [comment]
Yep. My bad, that's actually a typo. I've just checked that all the experiments were done with the `torch==1.10.1+cu111` version. I'll fix the README shortly. Thanks for the report!

**Comment by ekorman** [comment]
sweet, thanks for the quick response!
