### ISSUE TITLE
__init__() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by limengyang1992** [puhsu/tabular-dl-pretrain-objectives#3]
![image](https://user-images.githubusercontent.com/73928007/209625764-e9576d06-0e8d-43ac-a8c4-ced944b9c2bb.png)
I encountered the following error when running other programs.
Program: bin/rec.py   
Configuration: exp/rec/mlp-p-lr/california/3_tuning.toml

**Comment by puhsu** [comment]
Hey 👋  Thanks for your interest in the project!

The error is expected as you try to run the training script with the config for hyperparameter tuning. 

If you just want to run the `bin/rec.py` script with some default hyperparameters (or tuned hyperparameters from the paper), see the configs in `*_evaluation` folders for an example. (like [this one](https://github.com/puhsu/tabular-dl-pretrain-objectives/tree/master/exp/rec-sup/mlp/california/3_evaluation)). Unfortunately, there are no explicit toml configs sometimes, but the configs are in the respective `report.json` files. You could write them to toml's with the following code: 
```python
lib.dump_toml(lib.load_report('exp/rec/mlp/california/3_evaluation/0')['config'], '0.toml')
```

If you, instead, wish to tune hyperparameters, you could use the `bin/tune.py` script. Tuning configs specify which script to use for training in the `program` argument.

**Comment by puhsu** [comment]
Closing the issue as solved. Feel free to reopen If you still have problems reproducing the results!
